### ISSUE TITLE
feat: use `debug` namespace for inner transactions

### ISSUE THREAD

**Issue by kyscott18** [ponder-sh/ponder#1201]
We should move to the `debug` namespace because it is more performant and better supported by rpc providers. This will require some algorithmic changes. Mainly, `sync-historical` will have to iterate block by block, but can skip using `eth_getTransactionReceipt`.

### Tasks
- [ ] define new filter types #1198 
- [ ] create database migration
- [ ] update `sync-realtime`
- [ ] update `sync-historical`

### Helper functions
This is probably not a complete list, but I can envision us needing some of these:

- `shouldIncludeTrace()` A trace can succeed, error, or succeed and be the child of a trace that errored. This function should return true in the first case, and false otherwise.
- `getTraceCheckpoint()` Return the checkpoint for a trace. The difficult part of this is going to be the `executionIndex`. This is going to require ordering all traces in a transaction, using depth first search. It's gonna be a huge improvement over the previous design.
https://github.com/ponder-sh/ponder/blob/d143b990d9fbf1f299c4847ef5f93dbee3d7b1e9/packages/core/src/sync-store/index.ts#L725-L742

### Other notes
Is it possible to order traces and logs interweaved?
